apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3manager.fullname" . }}
  labels:
    {{- include "s3manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "s3manager.selectorLabels" . | nindent 4 }}