apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets
  namespace: s3
spec:
  provider: aws
  secretObjects:
  - secretName: db-secrets
    type: Opaque
    data:
    - objectName: DB_USER  
      key: DB_USER
    - objectName: DB_PASSWORD  
      key: DB_PASSWORD
    - objectName: DB_HOST  
      key: DB_HOST
    - objectName: DB_NAME  
      key: DB_NAME
  parameters:
    objects: |
        - objectName: "crdbcreds"
          objectType: "secretsmanager"
          jmesPath: 
            - path: user
              objectAlias: DB_USER
            - path: password
              objectAlias: DB_PASSWORD
            - path: host
              objectAlias: DB_HOST
            - path: name
              objectAlias: DB_NAME