apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-access
  namespace: s3
  labels:
    {{- include "s3manager.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::385861399472:role/KarpenterController
